name: Check format

on:
  push:
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        deno_version: 
          - 1.20.0
    runs-on: ubuntu-latest
    name: "Run Deno tests"
    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno_version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno_version }}
      - name: Check format
        run: |
          deno fmt --check
